version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    container_name: search_web

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - DB_CONNECTION=sqlsrv
      - DB_HOST=db
      - DB_PORT=1433
      - DB_DATABASE=search
      - DB_USERNAME=sa
      - DB_PASSWORD=1234abcD
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - elasticsearch
    container_name: search_app

  db:
    image: microsoft/mssql-server-linux:2017-CU13
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1234abcD
    ports:
      - "1433:1433"
    volumes:
      - ./docker/db/data/data:/var/opt/mssql/data
      - ./docker/db/data/log:/var/opt/mssql/log
      - ./docker/db/data/secrets:/var/opt/mssql/secrets
    container_name: search_db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
    depends_on:
      - db
    container_name: search_elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    container_name: search_kibana

  logstash:
    build:
      context: .
      dockerfile: ./docker/logstash/Dockerfile
    depends_on:
      - db
      - elasticsearch
    container_name: search_logstash
